// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/adnanahmady/go-websocket-chat/config"
	"github.com/adnanahmady/go-websocket-chat/internal/presentation"
	"github.com/adnanahmady/go-websocket-chat/pkg/applog"
	"github.com/adnanahmady/go-websocket-chat/pkg/request"
	"github.com/adnanahmady/go-websocket-chat/pkg/websocket"
	"github.com/google/wire"
)

// Injectors from wire.go:

func WireUpApp() (*App, error) {
	configConfig := config.GetConfig()
	appLogger := applog.NewAppLogger(configConfig)
	server := request.NewServer(configConfig, appLogger)
	hub := websocket.NewHub(appLogger)
	handler := presentation.NewHandler(hub)
	routes := presentation.NewRoutes(server, handler)
	app := &App{
		Config: configConfig,
		Logger: appLogger,
		Server: server,
		Routes: routes,
		Hub:    hub,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config *config.Config
	Logger *applog.AppLogger
	Server *request.Server
	Routes *presentation.Routes
	Hub    *websocket.Hub
}

var AppSet = wire.NewSet(applog.NewAppLogger, wire.Bind(new(applog.Logger), new(*applog.AppLogger)), config.GetConfig, request.NewServer, wire.Bind(new(request.Router), new(*request.Server)), websocket.NewHub, presentation.NewHandler, presentation.NewRoutes, wire.Struct(new(App), "*"))
