// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/adnanahmady/go-websocket-chat/config"
	"github.com/adnanahmady/go-websocket-chat/pkg/applog"
	"github.com/google/wire"
)

// Injectors from wire.go:

func WireUpApp() (*App, error) {
	configConfig := config.GetConfig()
	appLogger := applog.NewAppLogger(configConfig)
	app := &App{
		Config: configConfig,
		Logger: appLogger,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config *config.Config
	Logger *applog.AppLogger
}

var AppSet = wire.NewSet(applog.NewAppLogger, wire.Bind(new(applog.Logger), new(*applog.AppLogger)), config.GetConfig, wire.Struct(new(App), "*"))
